import { Playfair_Display, Noto_Sans } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/context/QueryProvider";

const heading = Playfair_Display({
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const normal = Noto_Sans({
  variable: "--font-normal",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${heading.variable} ${normal.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
